CREATE TABLE tb_ponto_coleta (
                                 id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 nome VARCHAR2(100) NOT NULL,
                                 endereco VARCHAR2(255) NOT NULL,
                                 tipo_material VARCHAR2(50) NOT NULL,
                                 capacidade_maxima_kg NUMBER(10,2) NOT NULL,
                                 capacidade_atual_kg NUMBER(10,2) DEFAULT 0.0
);

CREATE TABLE tb_agendamento_coleta (
                                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       ponto_coleta_id NUMBER NOT NULL,
                                       data_agendamento TIMESTAMP NOT NULL,
                                       status VARCHAR2(30) DEFAULT 'PENDENTE',
                                       CONSTRAINT fk_ponto_coleta FOREIGN KEY (ponto_coleta_id) REFERENCES tb_ponto_coleta(id)
);